### ISSUE TITLE
Problem with "with .. do .. using" block duplication

### ISSUE THREAD

**Issue by kbridson** [aolney/jupyterlab-blockly-python-extension#12] opened 2024-05-30 21:34 UTC
Sometimes the "with .. do .. using" block will generate a second copy of the base code when doing Blocks to Code. The duplicate block does not appear in the Blockly panel until you do Code to Blocks. Then you can delete it and do Blocks to Code again to fix.

<img width="1203" alt="Screen Shot 2024-05-29 at 1 55 36 PM" src="https://github.com/aolney/jupyterlab-blockly-python-extension/assets/21212136/8f1b3d64-2261-4b7b-be7c-5b7bc8e2de3d">

**Comment by aolney** [comment] 2024-06-03 22:04
I think Hasan said this was happening when the XML from a previous version was being deserialized to the new intelliblock with mutator arguments, and does not appear when using newly serialized XML. So closing as not a bug per se

**Closed as completed by aolney** 2024-06-03 22:04 UTC
Labels: wontfix
